### ISSUE TITLE
关于对星期计算的问题

### ISSUE THREAD

**Issue by HarryLin2** [coolapk-weather/Weather#2]
在我的系统里，星期的显示是错的（我的星期显示比正确的晚了一天），在网上搜了一下，http://chamcon.iteye.com/blog/2144433
应该是没有校验一周第一天是哪一天。

**Comment by ma-weihao** [comment]
明白了！确实搞错了



在 HarryLin2 <notifications@github.com>，2017年7月13日 下午7:02写道：

在我的系统里，星期的显示是错的，在网上搜了一下，http://chamcon.iteye.com/blog/2144433，应该是没有校验一周第一天是哪一天。<http://chamcon.iteye.com/blog/2144433%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%98%AF%E6%B2%A1%E6%9C%89%E6%A0%A1%E9%AA%8C%E4%B8%80%E5%91%A8%E7%AC%AC%E4%B8%80%E5%A4%A9%E6%98%AF%E5%93%AA%E4%B8%80%E5%A4%A9%E3%80%82>

（我的星期显示比正确的晚了一天）
